version: "3.3"
services:

  app:
    build:
        context: ./
        dockerfile: ./deploy/docker/Dockerfile
    volumes:
      - /etc/hostname:/etc/hostname:ro
    environment:
      - APP_NAME=${APP_NAME}
      - APP_ENV=${APP_ENV}
      - APP_KEY=${APP_KEY}
      - APP_DEBUG=${APP_DEBUG}
      - APP_LOG_LEVEL=${APP_LOG_LEVEL}
      - APP_URL=${APP_URL}
    ports:
      - "${APP_PORT:-8000}:80"
